name: "Publish .NET NuGet Package"
description: "Packs and publishes a .NET package to NuGet. Supports trusted publishing (OIDC) for nuget.org and authenticated publishing for other feeds."

inputs:
  working-directory:
    description: "The directory to run dotnet commands in"
    required: true
  use-trusted-publishing:
    description: "Use OIDC-based trusted publishing for nuget.org. Requires 'permissions: id-token: write' on the job. Set to 'false' for authenticated publishing to other feeds."
    default: "true"
  nuget-username:
    description: "Your nuget.org username. Required when use-trusted-publishing is 'true'."
    required: false
  nuget-auth-token:
    description: "The NuGet auth token. Required when use-trusted-publishing is 'false'."
    required: false
  source-url:
    description: "The source URL for the NuGet package feed. Override this when publishing to a non-nuget.org feed."
    default: "https://api.nuget.org/v3/index.json"
  dotnet-version:
    description: "The version of dotnet to use"
    default: "10.0.x"
  config-file:
    description: "Optional NuGet.config location, if your NuGet.config isn't located in the root of the repo."

runs:
  using: "composite"
  steps:
    # --- Trusted publishing path ---
    - name: Setup .NET SDK (trusted publishing)
      if: inputs.use-trusted-publishing == 'true'
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Login to NuGet with trusted publishing
      if: inputs.use-trusted-publishing == 'true'
      id: nuget-login
      uses: NuGet/login@v1
      with:
        user: ${{ inputs.nuget-username }}

    - name: Pack and publish NuGet package (trusted publishing)
      if: inputs.use-trusted-publishing == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        NUGET_API_KEY: ${{ steps.nuget-login.outputs.NUGET_API_KEY }}
      run: |
        dotnet pack -c Release
        dotnet nuget push "./bin/Release/*.nupkg" --api-key "$NUGET_API_KEY" --source "${{ inputs.source-url }}"

    # --- Authenticated publishing path ---
    - name: Setup .NET SDK (authenticated)
      if: inputs.use-trusted-publishing != 'true'
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        source-url: ${{ inputs.source-url }}
        config-file: ${{ inputs.config-file }}
      env:
        NUGET_AUTH_TOKEN: ${{ inputs.nuget-auth-token }}

    - name: Pack and publish NuGet package (authenticated)
      if: inputs.use-trusted-publishing != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        dotnet pack -c Release
        dotnet nuget push "./bin/Release/*.nupkg" --api-key "${{ inputs.nuget-auth-token }}" --source "${{ inputs.source-url }}"
