name: "Publish .NET NuGet Package"
description: "Packs and publishes a .NET package to NuGet if not already published"

inputs:
  working-directory:
    description: "The directory to run dotnet commands in"
    required: true
  nuget-auth-token:
    description: "The NuGet auth token"
    required: true
  source-url:
    description: "The source URL for the NuGet package feed"
    default: "https://pkgs.dev.azure.com/Atil-utvikling/Public/_packaging/AT.Public.NuGet/nuget/v3/index.json"
  dotnet-version:
    description: "The version of dotnet to use"
    default: "8.0.x"

runs:
  using: "composite"
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        source-url: ${{ inputs.source-url }}
      env:
        NUGET_AUTH_TOKEN: ${{ inputs.nuget-auth-token }}

    - name: Pack and publish NuGet package
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        dotnet pack -c Release
        dotnet nuget push "./bin/Release/*.nupkg" -k ArbitraryName --source "${{ inputs.source-url }}"
